[tool.poetry]
name = "CNN-Shape"
version = "0.0.1"
description = ""
authors = [
    "hihimamuLab"
]

[tool.poetry.dependencies]
python = "^3.6"
pysimplegui = "^4.60"

[tool.poetry.dev-dependencies]

[build-system]
require = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"